### ISSUE TITLE
Multiple Index Errors

### ISSUE THREAD

**Issue by killparty** [simianAstronaut/pi-hole-visualizer#5]
Those error messages appear when running the script. Switching through animations with the joystick doesn't work. Tested on Raspberry Pi 3 B+.

pi@raspberrypi:~/pi-hole-visualizer $ sudo ./dns_stats.py
Initiating connection with server.
Successful connection with server.
Traceback (most recent call last):
  File "./dns_stats.py", line 436, in <module>
    main()
  File "./dns_stats.py", line 432, in main
    event_loop(args, pw_hash)
  File "./dns_stats.py", line 361, in event_loop
    args.randomize)
  File "./dns_stats.py", line 97, in bar_chart_vertical
    domain_min = interval_data[0][0]
IndexError: list index out of range

**Comment by da9d** [comment]
Took a while, now it works fine.
